modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="soitsmods"
version="1.0.1"
displayName="SoItsMods"
updateJSONURL="https://github.com/soitsdragon/NeoForge-SoItsMods-1.21.X"
displayURL="https://soitsdragon.carrd.co/#"
logoFile="logo.png"
credits="SoItsDragon"
authors="SoItsDragon"
description="Please enjoy my first mod!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.soitsmods]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.soitsmods]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.soitsmods]]
    modId="nexus_compiler"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.soitsmods]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration