modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="soits_plushies"
version="1.0.4"
displayName="SoIts_Plushies"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="SoItsDragon"
authors="SoItsDragon"
description="Please enjoy my plushies!"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.soits_plushies]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.soits_plushies]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.soits_plushies]]
    modId="nexus_compiler"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.soits_plushies]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration